version: "2"

services:

  mysql:
    container_name: mysql_container
    image: mysql/mysql-server:5.7.20
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=footiedb
    volumes:
      - ./databaseSql/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    hostname: mysql-server

  jboss1:
    container_name: jboss_container1
    image: jboss/wildfly:12.0.0.Final
    volumes:
      - ./com/:/opt/jboss/wildfly/modules/com/
      - ./customization/:/opt/jboss/wildfly/customization/
      - ./warToBeDeployed/:/opt/jboss/wildfly/warToBeDeployed/
      - ./ha/:/opt/jboss/wildfly/ha/
    command: /opt/jboss/wildfly/customization/execute.sh
    tty: true
    network_mode: host

  jboss2:
     container_name: jboss_container2
     image: jboss/wildfly:12.0.0.Final
     volumes:
       - ./com/:/opt/jboss/wildfly/modules/com/
       - ./customization/:/opt/jboss/wildfly/customization/
       - ./warToBeDeployed/:/opt/jboss/wildfly/warToBeDeployed/
     command: /opt/jboss/wildfly/customization/execute2.sh
     tty: true
     network_mode: host