# Note (epaulki) Don't use container_name here as it will break CI's testRunner.sh script.

version: "2"

services:

  # Image Containing DPS and the Model Repo
  dps_integration:
    container_name: trs_dps_integration
    image: armdocker.rnd.ericsson.se/proj_oss_releases/enm/dps-prepopulated
    volumes:
      - /etc/opt/ericsson/ERICmodeldeployment/data
      - /etc/opt/ericsson/ERICmodeldeployment/models
      - /opt/ericsson/ERICdpsupgrade/egt/output
    hostname: db1-service

  # Image containing PostgreSQL Database Server used by Service Framework
  postgres:
    container_name: trs_postgres
    image: armdocker.rnd.ericsson.se/proj_oss_releases/enm/postgres
    hostname: postgresql-server

  # Image containing OpenDJ (LDAP Server) and all openidm policies
  opendj:
    container_name: trs_opendj
    image: armdocker.rnd.ericsson.se/proj_oss_releases/enm/access-control
    volumes:
      - ./docker/ldifs:/docker-entrypoint-init.d:ro

  # Apache docker image with mod_cluster enabled
  apache:
    container_name: trs_apache
    build: ./docker/apache-http-enm
    hostname: apache-host
    ports:
      - "6666:6666"
      - "80:80"
    volumes:
      - ./docker/apache-http-enm/config:/opt/ericsson/docker/config/httpd

  # Image containing JBoss AS server
  jboss:
    container_name: trs_jboss
    build: ./docker/jboss-image
    links:
      - postgres:postgresql-server
      - dps_integration:db1-service
      - opendj:ldap-remote
      - opendj:ldap-local
      - apache:apache-host
    volumes_from:
      - dps_integration
      - opendj
    environment:
      - JAVA_OPTS=-Xms2800m -Xmx2800m -XX:PermSize=256m -XX:MaxPermSize=768m -Ddps_ignore_mediation=true -Ddata.creator.group=trs-bit
    ports:
      - "9999:9999"
      - "9990:9990"
      - "8080:8080"
      - "8787:8787"
    volumes:
      - ./docker/jboss-image/config:/opt/ericsson/docker/config
